version: '3.8'
services:
  springboot-app:
    build: .
    ports:
      - "6000:6000"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
